<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>WinExe</OutputType>
        <TargetFramework>net8.0-windows</TargetFramework>
        <Nullable>enable</Nullable>
        <UseWindowsForms>true</UseWindowsForms>
        <ImplicitUsings>enable</ImplicitUsings>
        <Version>1.2.2</Version>
        <FileVersion>1.2.2.0</FileVersion>
        <AssemblyVersion>1.2.2.0</AssemblyVersion>
        <InformationalVersion>1.2.2+local</InformationalVersion>
        <TreatWarningsAsErrors>false</TreatWarningsAsErrors>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="ClosedXML" Version="0.105.0" />
        <PackageReference Include="Microsoft.Web.WebView2" Version="1.0.2849.39" />
        <PackageReference Include="Selenium.Support" Version="4.35.0" />
        <PackageReference Include="Selenium.WebDriver" Version="4.35.0" />
        <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="139.0.7258.15400" />
        <PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
    </ItemGroup>

    <Target Name="RemoveUnusedBuildArtifacts" AfterTargets="Build">
        <ItemGroup>
            <UnusedBuildArtifacts Include="$(OutDir)Microsoft.Web.WebView2.Wpf.dll" />
            <UnusedBuildArtifacts Include="$(OutDir)Microsoft.Web.WebView2.Wpf.xml" />
            <UnusedBuildArtifacts Include="$(OutDir)Microsoft.Web.WebView2.Core.xml" />
            <UnusedBuildArtifacts Include="$(OutDir)Microsoft.Web.WebView2.WinForms.xml" />
        </ItemGroup>
        <Delete Files="@(UnusedBuildArtifacts)" TreatErrorsAsWarnings="true" />
    </Target>

    <Target Name="RemoveUnusedPublishArtifacts" AfterTargets="Publish">
        <ItemGroup>
            <UnusedPublishArtifacts Include="$(PublishDir)Microsoft.Web.WebView2.Wpf.dll" />
            <UnusedPublishArtifacts Include="$(PublishDir)Microsoft.Web.WebView2.Wpf.xml" />
            <UnusedPublishArtifacts Include="$(PublishDir)Microsoft.Web.WebView2.Core.xml" />
            <UnusedPublishArtifacts Include="$(PublishDir)Microsoft.Web.WebView2.WinForms.xml" />
        </ItemGroup>
        <Delete Files="@(UnusedPublishArtifacts)" TreatErrorsAsWarnings="true" />
    </Target>

</Project>
